image: atlassian/default-image:2
pipelines:
  custom:
    default: &default-step
      - step:
          caches:
            - petsc-double-direct
          script:
            # Packages
            - apt-get update
            - apt-get --fix-missing -yq --no-install-suggests --no-install-recommends --force-yes install libblas-dev liblapack-dev

            # PETSc with SUNDIALS quad/direct hacks
            # Bitbucket may have restored the build from cache, so check before rebuilding
            - export PETSC_DIR=$PWD/petsc-double-direct
            - export PETSC_ARCH=arch-test
            - if [ -f "$PETSC_DIR/configure.log" ]; then export PETSC_ALREADY_HERE=y; else export PETSC_ALREADY_HERE=n; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then git clone https://bitbucket.org/psanan/petsc --depth=1 -b psanan/ts-sundials-quad-hack petsc-double-direct; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then cd $PETSC_DIR; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then ./configure --with-fc=0 --with-cxx=0 --with-cc=gcc --download-sundials --download-mpich; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then make all; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then make test; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then cd ..; fi

            # Build SPIDER
            - make -j

            # Run test with SciATH
            - git clone https://github.com/sciath/sciath tests/sciath --depth=1
            - export PYTHONPATH=$PYTHONPATH:$PWD/tests/sciath
            - mkdir test_dir
            - cd test_dir && python -m sciath -d # create default config
            - cd test_dir && python -m sciath ../tests/tests.yml -t blackbody_short -f
          artifacts:
            - test_dir/**

  branches:
    master: *default-step
definitions:
   caches:
      petsc-double-direct: petsc-double-direct
