pipelines:
  branches:
    master:
      - step:
          caches:
            - petsc-double-direct
          script:
            # Packages
            - sudo apt-get update
            - sudo apt-get --fix-missing -yq --no-install-suggests --no-install-recommends --force-yes install libblas-dev liblapack-dev python-numpy

            # PETSc with SUNDIALS quad/direct hacks
            # Bitbucket may have restored the build from cache, so check before rebuilding
            - export PETSC_DIR=$PWD/petsc-double-direct
            - export PETSC_ARCH=arch-test
            - if [ -f "$PETSC_DIR/configure.log" ]; then export PETSC_ALREADY_HERE=y; else export PETSC_ALREADY_HERE=n; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then git clone https://bitbucket.org/psanan/petsc --depth=1 -b psanan/ts-sundials-quad-hack petsc-double-direct; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then cd $PETSC_DIR; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then ./configure --with-fc=0 --with-cxx=0 --with-cc=gcc --download-sundials --download-mpich; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then make all; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then make test; fi
            - if [ "$PETSC_ALREADY_HERE" = "n" ]; then cd ..; fi

            # Build SPIDER
            - make -j

            # Test
            - cd tests
            - git clone https://bitbucket.org/dmay/pythontestharness
            - ./runTests.py -d # create default config
            - ./runTests.py -f # Return error code based on test success
definitions:
   caches:
      petsc-double-direct: petsc-double-direct
