name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python requirements
      run: |
        pip install -r py/requirements.txt
        sudo apt-get install texlive-base texlive-fonts-recommended
    - name: PETSc cache
      id: petsc-cache
      uses: actions/cache@v2
      with:
        path: petsc
        key: ${{ runner.os }}-petsc
    - name: Build PETSc
      if: steps.petsc-cache.outputs.cache-hit != 'true'
      run: |
          git clone https://gitlab.com/petsc/petsc.git --depth=1 -b psanan/ts-sundials-dense-2  # FIXME update
          cd petsc
          ./configure --with-fc=0 --with-cxx=0 --with-cc=gcc --download-sundials2 --download-mpich PETSC_ARCH=arch-test
          make all
    - name: make
      run: PETSC_DIR=petsc PETSC_ARCH=arch-test make
    - name: Test with SciATH
      run: |
          cd tests && git clone https://github.com/sciath/sciath --depth=1 && cd -
          export PYTHONPATH=$PYTHONPATH:$PWD/tests/sciath
          mkdir -p test_dir && cd test_dir
          python -m sciath -d -w pth.conf
          python -m sciath -f -w pth.conf ../tests/tests.yml
    - name: Archive test results
      uses: actions/upload-artifact@v2
      if : always()
      with:
        name: spider-sciath-test-dir
        path: test_dir
