name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PETSc cache
      id: petsc-cache
      uses: actions/cache@v2
      with:
        path: petsc
        key: ${{ runner.os }}-petsc
    - name: Build PETSc
      if: steps.petsc-cache.outputs.cache-hit != 'true'
      run: |
          git clone https://gitlab.com/petsc/petsc.git --depth=1 -b psanan/ts-sundials-dense-2  # FIXME update
          cd petsc
          ./configure --with-fc=0 --with-cxx=0 --with-cc=gcc --download-sundials2 --download-mpich PETSC_ARCH=arch-test
          make all
    - name: make
      run: PETSC_DIR=petsc PETSC_ARCH=arch-test make
    - name: install SCiATH
      run: cd tests && git clone https://github.com/sciath/sciath --depth=1
    - name: make test
      run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/tests/sciath
          mkdir -p test_dir && cd test_dir
          python -m sciath -d -w pth.conf  # default config
          python -m sciath -f -w pth.conf  # fun tests and produce error code
